
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const PeriodType = {
  YEAR: 'YEAR',
  MONTH: 'MONTH',
  WEEK: 'WEEK'
} as const

export type PeriodType = (typeof PeriodType)[keyof typeof PeriodType]


export const FolderType = {
  SCENE: 'SCENE',
  GROUP: 'GROUP',
  PROJECT: 'PROJECT',
  SUBPROJECT: 'SUBPROJECT'
} as const

export type FolderType = (typeof FolderType)[keyof typeof FolderType]
